use_default_settings: true

general:
  instance_name: "str-revenue-searxng"

server:
  secret_key: "4e7e39fc3a6585e4233f4ec319636755f1a8f83abb40cd41b66ec54cf8e3f075"
  limiter: false
  image_proxy: false

search:
  formats:
    - html
    - json

outgoing:
  proxies:
    all://:
      - socks5h://tor:9050
  using_tor_proxy: true
  request_timeout: 10.0

engines:
  - name: google
    engine: google
    shortcut: go
    disabled: false

  - name: bing
    engine: bing
    shortcut: bi
    disabled: false

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg
    disabled: false

  - name: brave
    engine: brave
    shortcut: br
    disabled: false

  - name: qwant
    engine: qwant
    shortcut: qw
    disabled: false

  - name: mojeek
    engine: mojeek
    shortcut: mj
    disabled: false

  - name: startpage
    engine: startpage
    shortcut: sp
    disabled: false
